### ISSUE TITLE
Word counter displaying negative words left

### ISSUE THREAD

**Issue by thomasfrivold** [kasperisager/vanilla-wordcount#5]
Hi

Running Vanilla 2.1.10 and Word Count 2.1.0 and I have enabled the CreativeCLEditor version 1.2.1.
When I type something in my forum, I see a negative word counter. This is confusing me and my users a bit.

Is there a way to disable "Characters remaining" text and counter? 

I only need the word counter...!

![image](https://cloud.githubusercontent.com/assets/1677630/7817064/7c71fc26-03d2-11e5-9f95-045d2b6864c9.png)

Thanks for your help and for making the plugin!

**Comment by kasperisager** [comment]
You'd have to remove the character counter here: https://github.com/kasperisager/vanilla-wordcount/blob/master/js/initialize.js#L16-L22
